[Feat] 고민글 전체 조회 구현 , API 테스트파일 생성
TeamHARA/HARA_SERVER pull request #11
Opened 2023-01-05 12:33 UTC by yujindonut

**우선순위**

D-0

**변경사항**
- 고민글 전체 조회 구현
- supertest로 API 테스트 파일 생성했습니다.

**유의사항**

responseMessage를 구현하기 위해서, flattening을 하기 위해서 Response메세지 객체를 하나 더 구현했습니다. 
이 부분이 중복적으로 사용되고, DTO 파일을 이용해 구현하는 방법이 있을 것 같은데, 이 부분들을 DTO로 구현할 수 있을까요?
------------------------------------------------------------------------
categoryId가 0번일때는 전체 카테고리 조회인데, 이 부분 구현 부분을 두가지로 나누었는데, 이부분이 맞는지 확신이 서지 않습니다..

worryService.ts 파일의 부분입니다.

```Javascript
const getWorryListByCategoryId = async (categoryId: number) => {
const worryWithList = (categoryId == 0) ? await worryRepository.getWorries() : await worryRepository.getWorryListByCategoryId(categoryId);
```
더 좋은 방안이 있다면 알려주시면 감사하겠습니당 🥰

**참조**

- `localhost:3000/api/worry/0` : 전체 카테고리 조회

<img width="704" alt="image" src="https://user-images.githubusercontent.com/78431728/210780923-a14290a9-1daa-4953-9f95-dd70ad42e858.png">

- `localhost:3000/api/worry/1` : 1번째 카테고리 조회

<img width="693" alt="image" src="https://user-images.githubusercontent.com/78431728/210781110-e744d323-1cd5-4c20-bb64-6257d75b4385.png">

- jest 테스트 성공

<img width="674" alt="image" src="https://user-images.githubusercontent.com/78431728/210780338-09b96950-1c26-40a1-aac6-e3f96f2ad1cd.png">

2023-01-05 15:56 UTC, kyY00n requested changes
수고하셨어요! 코멘트 남겼습니당 ><

2023-01-05 15:56 UTC, kyY00n commented on src/constants/responseMessage.ts
> +  READ_CATEGORY_FAIL: "없는 카테고리번호 입니다.",
p.2 변수명의 의미가 메시지를 충분히 표현하지 못한 것 같아요

2023-01-05 15:56 UTC, kyY00n commented on src/controller/worryController.ts
> +        return res.status(sc.BAD_REQUEST).send(fail(sc.BAD_REQUEST, rm.READ_WORRYLIST_FAIL));
p1. 작성해주신 코드는 controller 하위에서 발생한 모든 예외에 대해 같은 응답을 보내게 되는 문제가 있어요.

```suggestion
const getWorryListByCategory = async (req: Request, res: Response, next: NextFunction) => {
   // ...
    try {
        // ...
    } catch (error) {
        next(error);
       }
   }
```
이렇게 하면, 미들웨어에 등록돼있는 에러 핸들러(/common/error/handler.ts) 에서 응답을 보내주어요.
우리가 예상한 예외가 아닌 경우에도 처리를 해주고, 우리가 던진 예외마다 정의한 status code로 응답해줄 수 있어요.

만약 우리가
```typescript
throw new ClientExcpetion("걱정 글 삭제 권한이 없습니다.", 403);
```
이렇게 예외를 던진다면, 우리의 에러 핸들러가
```typescript
res.status(status).send(fail(403, "걱정 글 삭제 권한이 없습니다."));
```
이렇게 응답해줘용

2023-01-05 15:56 UTC, kyY00n commented on src/service/worryService.ts
> +    const worryWithList = (categoryId == 0) ? await worryRepository.getWorries() : await worryRepository.getWorryListByCategoryId(categoryId);
p3. 전 이렇게 해도 상관 없을 것 같아요! 근데 조건문의 의미가 모호하니 저라면 함수로 빼주겠어요 ㅎㅎ
```suggestion
 const isTotal(category: number): boolean => categoryId === 0;
 
 const getWorryListByCategoryId = async (categoryId: number) => {
    const worryWithList = isTotal(categoryId) ? await worryRepository.getWorries() : await 
    worryRepository.getWorryListByCategoryId(categoryId);
    // ...
 }
```

2023-01-05 15:56 UTC, kyY00n commented on test/controller/worryController.spec.ts
> +        expect(response.body.message).toEqual("고민글 조회 성공");
p4. 앱잼 기간에는 간단하게 테스트를 작성하는 것이 좋긴하지만, 이런 조회 api의 경우에는 반환하는 결과가 중요하기 때문에 결과를 검증하는 로직도 추가해주면 좋습니다.

2023-01-05 15:56 UTC, kyY00n commented on test/controller/worryController.spec.ts
> +    it("잘못된 응답", async () => {
p2. describe - context - it 패턴을 조사해보세요.
지금 이 코드를 봤을 때는 '왜' 잘못된 응답이 나오는지 알수 없어요.
어떤 조건을 두었는지 코드로 표현해주면 더 좋은 테스트 코드가 될 것 같습니다.

2023-01-06 00:56 UTC, yujindonut commented on src/service/worryService.ts
> +    const worryWithList = (categoryId == 0) ? await worryRepository.getWorries() : await worryRepository.getWorryListByCategoryId(categoryId);
훨씬 이해하기 좋은 코드인것 같습니다..!!!!!! 감사합니다~!~!~!

2023-01-06 01:21 UTC, yujindonut commented on src/controller/worryController.ts
> +        return res.status(sc.BAD_REQUEST).send(fail(sc.BAD_REQUEST, rm.READ_WORRYLIST_FAIL));
와 상세한 답변 감사해요 .. 에러핸들러 짱짱이네요 ..

2023-01-06 03:54 UTC, kyY00n commented on test/controller/worryController.spec.ts
> +        // expect(response.body).toMatchObject({
이거 왜 주석처리 돼있눈고야?

2023-01-06 03:55 UTC, kyY00n approved these changes
수고많았어여!!!! 유진 정말 pr도 잘 써주고 피드백도 바로 이해하구 반영해줘서 고마워 ><

2023-01-06 05:09 UTC, merged

2023-01-06 14:12 UTC, yujindonut commented on test/controller/worryController.spec.ts
> +        // expect(response.body).toMatchObject({
허엉 이거 지금 봤다!! 이거 값이 db에 값이 추가되면 더 추가된 것으로 body값 예상해서, db에 데이터 쌓일때마다 test코드 바꿔줘야해성 ><,,,,

2023-01-06 14:15 UTC, yujindonut commented on test/controller/worryController.spec.ts
> +    it("잘못된 응답", async () => {
https://johngrib.github.io/wiki/junit5-nested/
Describe - 설명할 테스트 대상을 명시한다.
Context - 테스트 대상이 놓인 상황을 설명한다
It - 테스트 대상의 행동을 설명한다.