[FEAT] 함께고민글 상세조회
TeamHARA/HARA_SERVER pull request #23
Opened 2023-01-07 04:35 UTC by leGit-y

**우선순위**
1순위

D-1

**변경사항**
함께고민글 상세조회하는 기능 구현했습니다.
<성공시>
<img width="970" alt="image" src="https://user-images.githubusercontent.com/99312658/211131065-6454e24e-6dd1-42e8-95ad-533937422164.png">

<실패시>
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/99312658/211131145-2aafaaa8-1b9a-4cf7-b95d-1cf047576324.png">

**유의사항**

**참조**

2023-01-07 08:58 UTC, kyY00n requested changes
코멘트 남겼습니당! 수고했어요😃

2023-01-07 08:58 UTC, kyY00n commented on src/controller/worryWithController.ts
>      }
이거도 express validator 사용 가능하지 않나요!?
그냥 궁금쓰. 이건 괜찮고! 다음엔 한번 적용해보세요~~ 만들어둔 거 재사용하는 쾌감><

2023-01-07 08:58 UTC, kyY00n commented on src/repository/worryWithRepository.ts
> +  });
p1. 이건 withOptionRepository에 구현하는게 좋지 않을까요?

2023-01-07 08:58 UTC, kyY00n commented on src/service/worryWithService.ts
> +  console.log(findWithWorryData);
p1. 출력문 지워주세요@

2023-01-07 13:31 UTC, csb9427 reviewed
고생하셨습니다!

2023-01-07 13:31 UTC, csb9427 commented on src/controller/worryWithController.ts
> +const getWithWorryDetail =async (req:Request, res: Response, next: NextFunction) => {
더 직관적인 변수명으로 변경하는 모습 보기 좋습니다.!

2023-01-08 08:52 UTC, leGit-y commented on src/repository/worryWithRepository.ts
> +  });
아 맞네요! 수정하겠습니다 :)

2023-01-08 10:00 UTC, leGit-y commented on src/controller/worryWithController.ts
>      }
근데 생각해보니 해당 에러가 발생할 상황이 있나..?
[GET] api/worry/with/:worryId 랑
[GET] api/worry/with 가 있는데
worryId에 해당하는 파라미터 값을 뺴먹으면 밑에 라우터로 적용되는거 아닌가,,?

2023-01-08 14:32 UTC, kyY00n approved these changes
굳굳 늦어서 쏘리

2023-01-08 14:35 UTC, merged