Feature/#2 post worry alone
TeamHARA/HARA_SERVER pull request #8
Opened 2023-01-05 10:23 UTC by leGit-y

**우선순위**
0순위

D-1

**변경사항**
worryAlone - Router, Controller, Service, Repository 생성
혼자고민생성 API 구현

**유의사항**

controller, service 에서 각각 어떠한 에러처리를 해줘야 하는지...

**참조**

2023-01-05 10:27 UTC, leGit-y commented on src/controller/worryAloneController.ts
> +
worryAloneController - req.body 값 중 필요한값이 비어있는지를 확인하는 에러처리 구문에서 저렇게 각각 비어있는지 체크하는 방법 말고 DTO통째로 유효성 검사를 진행하는 방식을 알고 있는 분 계신가요,,,

2023-01-05 14:00 UTC, csb9427 commented on src/controller/worryAloneController.ts
> +
https://vvs1.tistory.com/141
이 블로그 보면 Controller에서 하는 것보다 Router에서 하는 방법 및 express-validator 사용법이 나와있습니다! 참고하고 말씀해주세요!!

2023-01-05 14:57 UTC, kyY00n requested changes
수고하셨습니다👏🏻 코멘트 남겼어요

2023-01-05 14:57 UTC, kyY00n commented on src/controller/worryAloneController.ts
> +    //? validation의 결과를 바탕으로 분기 처리
주석 삭제 plz

2023-01-05 14:57 UTC, kyY00n commented on src/controller/worryAloneController.ts
> +
승빈오빠가 얘기한거 써줬네 그럼 검증 다 된거같은데!

2023-01-05 14:57 UTC, kyY00n commented on src/controller/worryAloneController.ts
> +    const data = await worryAloneService.uploadWorryAlone(uploadWorryAloneDTO);
P3. 변수명이 모호합니당.
```suggestion
    const createdWorryAlone = await worryAloneService.uploadWorryAlone(uploadWorryAloneDTO);
```

2023-01-05 14:57 UTC, kyY00n commented on src/router/worryAloneRouter.ts
> +router.post("/",worryAloneController.uploadWorryAlone);
p1. auth 미들웨어 집어넣어주세용

2023-01-05 14:57 UTC, kyY00n commented on src/controller/worryAloneController.ts
> +
그럼 20-24 지워도 되는 것 아닌가요?

2023-01-06 09:24 UTC, kyY00n requested changes
속도도 빠르고 이제 잘 적응한 것 같아용!!! 유진 무서운 성장캐군요
코멘트 달았습니당 ㅎㅎ

2023-01-06 12:19 UTC, kyY00n approved these changes
LGTM 👍🏻

2023-01-06 14:09 UTC, merged